- name: Home
  width: slim
  center-vertical: true
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  hide-desktop-navigation: true
  columns:
    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Pi-Hole
              url: http://homepi.local:8000/
              check-url: http://homepi.local:8000/
              icon: si:pihole
    - size: small
      widgets:
        - type: weather
          location: Rio de Janeiro, Brazil
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true
        - type: calendar
          first-day-of-week: monday
        - type: markets
          markets:
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: WEX
              name: WEX Inc.
