- name: Home
  width: slim
  center-vertical: true
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  hide-desktop-navigation: true
  columns:
    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: DNS (homepi.net)
          sites:
            - title: cockpit.homepi.net
              url: http://cockpit.homepi.net/
              check-url: http://cockpit.homepi.net/
              icon: si:cloudflare
            - title: pihole.homepi.net
              url: http://pihole.homepi.net/admin
              check-url: http://pihole.homepi.net/admin
              icon: si:cloudflare
            - title: portainer.homepi.net
              url: http://portainer.homepi.net/
              check-url: http://portainer.homepi.net/
              icon: si:cloudflare
            - title: grafana.homepi.net
              url: http://grafana.homepi.net/
              check-url: http://grafana.homepi.net/
              icon: si:cloudflare
            - title: pgadmin.homepi.net
              url: http://pgadmin.homepi.net/
              check-url: http://pgadmin.homepi.net/
              icon: si:cloudflare
            - title: api.homepi.net
              url: http://api.homepi.net/up
              check-url: http://api.homepi.net/up
              icon: si:cloudflare
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Cockpit
              url: http://192.168.1.100:7999/
              check-url: http://192.168.1.100:7999/
              icon: si:cockpit
            - title: Pi-Hole
              url: http://192.168.1.100:8000/admin
              check-url: http://192.168.1.100:8000/admin
              icon: si:pihole
            - title: Portainer
              url: http://192.168.1.100:8003/
              check-url: http://192.168.1.100:8003/
              icon: si:portainer
            - title: Grafana
              url: http://192.168.1.100:3000/
              check-url: http://192.168.1.100:3000/
              icon: si:grafana
        - type: monitor
          cache: 1m
          title: Databases
          sites:
            - title: Postgres
              url: http://192.168.1.100:5432/
              check-url: http://192.168.1.100:3001/api/v1/check/postgres
              icon: si:postgresql
            - title: PGAdmin
              url: http://192.168.1.100:4000/
              check-url: http://192.168.1.100:4000/
              icon: si:adminer
            - title: Redis
              url: http://192.168.1.100:6379/
              check-url: http://192.168.1.100:3001/api/v1/check/redis
              icon: si:redis
        - type: monitor
          cache: 1m
          title: APIs
          sites:
            - title: Health Check API
              url: http://192.168.1.100:3001/docs
              check-url: http://192.168.1.100:3001/up
              icon: si:fastapi
            - title: Football Fan API
              url: http://192.168.1.100:3002/docs
              check-url: http://192.168.1.100:3002/up
              icon: si:fastapi
    - size: small
      widgets:
        - type: weather
          location: Rio de Janeiro, Brazil
          units: metric # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true
        - type: calendar
          first-day-of-week: monday
        - type: markets
          markets:
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: NVDA
              name: NVIDIA
            - symbol: AAPL
              name: Apple
            - symbol: WEX
              name: WEX Inc.
