services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    privileged: true
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    depends_on:
      - nginx
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
      - "443:443" # Optional, for HTTPS
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom Nginx configuration
      - ./html:/usr/share/nginx/html:ro # Mount static content

