services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro # Mount custom Nginx configuration
      - ./html:/usr/share/nginx/html:ro # Mount static content

